name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    # - name: Set PYTHONPATH
    #   run: |
    #     export PYTHONPATH="$PYTHONPATH:/."

    - name: Install pytest
      run: python -m pip install pytest
      

    - name: Run Tests
      run: PYTHONPATH=. pytest test_cal.py